# Generated by Django 2.2.28 on 2022-10-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressyjotwmteyf'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressyjotwmteyf',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
